# Generated by Django 4.2.5 on 2023-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('genre', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('year_release', models.PositiveIntegerField()),
                ('metacritic_rating', models.FloatField()),
                ('runtime', models.PositiveIntegerField()),
            ],
        ),
    ]
